/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.8
 * Generated at: 2017-02-18 07:29:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import com.database.DatabaseConnection;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.database.DatabaseConnection");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Add Employee</title>\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.12.4-jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"css/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/raterater.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"js/raterater.jquery.js\"></script>\r\n");
      out.write("    <!-- Custom Fonts -->\r\n");
      out.write("    <link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <script>\r\n");
      out.write("    window.open (\"FaceMood.jsp\",\"mywindow\");\r\n");
      out.write("\t    $(document).ready(function(){\r\n");
      out.write("/* \t        $(\".sideM\").removeClass('active');\r\n");
      out.write("\t        $(\".itemM\").addClass('active');\r\n");
      out.write("\t        getHotelItemList(); */\r\n");
      out.write("\t    \t$('.datep').datepicker({\r\n");
      out.write("\t    \t\tformat : 'dd-mm-yyyy',\r\n");
      out.write("\t             autoclose:true\r\n");
      out.write("\t     \t});\r\n");
      out.write("\t        \r\n");
      out.write("\t    \t$( '.ratebox' ).raterater( { \r\n");
      out.write("               // submitFunction: 'rateAlert',\r\n");
      out.write("                allowChange: false,\r\n");
      out.write("                isStatic: true,\r\n");
      out.write("\r\n");
      out.write("                starWidth: 20,\r\n");
      out.write("                spaceWidth: 10,\r\n");
      out.write("                numStars: 5\r\n");
      out.write("            } );\r\n");
      out.write("\t        \r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    function getItem(itemId){\r\n");
      out.write("\t    \t$.ajax({\r\n");
      out.write("    \t\t   url: 'getHotelItem.htm',\r\n");
      out.write("    \t\t   data: {itemId:itemId},\r\n");
      out.write("    \t\t   type: 'GET',\r\n");
      out.write("    \t\t   dataType: 'json',\r\n");
      out.write("    \t\t   error: function() {\r\n");
      out.write("    \t\t      $('#info').html('<p>An error has occurred</p>');\r\n");
      out.write("    \t\t   },\r\n");
      out.write("    \t\t   success: function(data) {\r\n");
      out.write("    \t\t\t   $(\"input[name='itemName']\").val(data.itemName);\r\n");
      out.write("    \t\t\t   $(\".description\").val(data.description);\r\n");
      out.write("    \t\t\t   $(\"input[name='price']\").val(data.price);\r\n");
      out.write("    \t\t\t   $(\".hid_itemId\").val(itemId);\r\n");
      out.write("    \t\t\t   $(\".btn-addItem\").html(\"Update\");\r\n");
      out.write("    \t\t   },\r\n");
      out.write("    \t\t});\r\n");
      out.write("\t    }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");




HttpSession session1 = request.getSession(false);

if(session1.getAttribute("username") == null)
{
	response.sendRedirect("Login.jsp");
}
else
{
String eid=session.getAttribute("eid").toString();
DatabaseConnection db=new DatabaseConnection();
ResultSet rs=db.selectQuery("select rank from employee where eid="+eid+"");
int rank=0;
if(rs.next()){
	rank=rs.getInt("rank");

}


      out.write("\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header1.jsp", out, false);
      out.write("\r\n");
      out.write("    <div id=\"page-wrapper\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("<!--     \t<div class=\"panel panel-default col-sm-12\">\r\n");
      out.write("        \t<div class=\"panel-heading\">Login</div>-->\r\n");
      out.write("          \t<div class=\"panel-body\" > \r\n");
      out.write("          \t          \t<h3> Rating :\t");
      out.print(rank);
      out.write(" </h3>  <br/> <br/>\r\n");
      out.write("           \t        <img src=\"fonts/slide.jpg\" width=\"100%\" height=\"150%\"/>\r\n");
      out.write("          \t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

	
}


      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
