/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.8
 * Generated at: 2017-01-02 09:47:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!--\n");
      out.write("Author: W3layouts\n");
      out.write("Author URL: http://w3layouts.com\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\n");
      out.write("-->\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Alley Signup & Signin Form Responsive Widget Template  :: w3layouts</title>\n");
      out.write("<link href=\"css/style.css\" rel='stylesheet' type='text/css'>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("<meta name=\"keywords\" content=\"Alley Signup & Signin Form Tab Form,Login Forms,Sign up Forms,Registration Forms,News letter Forms,Elements\" ./=\"\">\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\n");
      out.write("\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\n");
      out.write("<script src=\"js/easyResponsiveTabs.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\t$(document).ready(function () {\n");
      out.write("\t\t\t\t\t\t$('#horizontalTab').easyResponsiveTabs({\n");
      out.write("\t\t\t\t\t\t\ttype: 'default', //Types: default, vertical, accordion           \n");
      out.write("\t\t\t\t\t\t\twidth: 'auto', //auto or any width like 600px\n");
      out.write("\t\t\t\t\t\t\tfit: true   // 100% fit in a container\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t   </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("\n");
      out.write("<!---728x90--->\n");
      out.write(" \n");
      out.write("\t<h1> Employee Management\t </h1>\n");
      out.write("<!---728x90--->\n");
      out.write(" \n");
      out.write("<div class=\"main-content\">\n");
      out.write("\t<div class=\"sap_tabs\">\t\n");
      out.write("\t\t \n");
      out.write("\t\t<div id=\"horizontalTab\" style=\"display: block; width: 100%; margin: 0px;\">\n");
      out.write("\t\t \n");
      out.write("\t\t\t  <ul>\n");
      out.write("\t\t\t  \t  <li class=\"resp-tab-item\" aria-controls=\"tab_item-0\" role=\"tab\"><span>User Credential</span></li>\n");
      out.write("<!-- \t\t\t\t  <li class=\"resp-tab-item\" aria-controls=\"tab_item-1\" role=\"tab\"><span>Sign in</span></li>\n");
      out.write(" -->\t\t\t\t  \n");
      out.write("\t\t\t  </ul>\t\t\n");
      out.write("\t\t\t  <!---->\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"tab-1 resp-tab-content\" aria-labelledby=\"tab_item-0\">\n");
      out.write("\t\t\t\t<div class=\"facts\">\n");
      out.write("\t\t\t\t\t<div class=\"register\">\n");
      out.write("\t\t\t\t\t\t<form action=\"LoginServlet\"  method=\"post\">\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<input placeholder=\"Email Address\" name=\"username\" class=\"mail\" type=\"text\" required>\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<input placeholder=\"Password\" class=\"lock\" name=\"password\" type=\"password\" required>\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sign-up\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Sign in\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<br/> <br/>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t");

							
							    if(session.getAttribute("status") != null)
							    {
							
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<font color=\"white\" size=\"5\">");
      out.print( session.getAttribute("status").toString() );
      out.write("</font>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t");

							
							
							    }
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div> \n");
      out.write("\t\t\t</div>\t\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"tab-2 resp-tab-content\" aria-labelledby=\"tab_item-1\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"facts\">\n");
      out.write("\t\t\t\t\t<!--login1-->\n");
      out.write("\t\t\t\t\t<div class=\"register\">\n");
      out.write("\t\t\t\t\t\t<form>\t\n");
      out.write("\t\t\t\t\t\t\t<input placeholder=\"Name\" name=\"name\" id=\"name\" type=\"text\" required pattern=\"[a-zA-Z]+\\s[a-zA-Z]+\\s[a-zA-Z]+\">\n");
      out.write("\t\t\t\t\t\t\t<input placeholder=\"Email Address\" name=\"email\" id=\"email\" type=\"email\" required>\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<input placeholder=\"Password\" type=\"password\" name=\"password1\" id=\"password1\" required title=\"Atleast 1 Capital letter, 1 special symbol and 1 number and no spaces\" pattern=\"^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\\s).*$\">\t\n");
      out.write("\t\t\t\t\t\t\t<input placeholder=\"Confirm Password\" type=\"password\" name=\"conPassword\" id=\"conPassword\" required title=\"Atleast 1 Capital letter, 1 special symbol and 1 number and no spaces\" pattern=\"^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\\s).*$\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sign-up\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Create Account\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div> \t\t\t        \t\t\t\t\t            \t      \n");
      out.write("\t\t\t \t\n");
      out.write("\t\t</div>\t\n");
      out.write("\t\t\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!---728x90--->\n");
      out.write("<div style=\"text-align: center;\"><script async=\"\" src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"></script>\n");
      out.write("<ins class=\"adsbygoogle\" style=\"display:inline-block;width:728px;height:90px\" data-ad-client=\"ca-pub-9153409599391170\" data-ad-slot=\"6850850687\"></ins>\n");
      out.write("<script>\n");
      out.write(" </script></div>\n");
      out.write("\t <!--start-copyright-->\n");
      out.write("   \t\t<div class=\"copy-right\">\n");
      out.write("   \t\t\t \n");
      out.write("\t\t</div>\n");
      out.write("\t<!--//end-copyright-->\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write(" \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
