/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.8
 * Generated at: 2017-02-18 11:30:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import com.database.DatabaseConnection;

public final class employeeList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.database.DatabaseConnection");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Add Employee</title>\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"bootstrap-datepicker.js\"></script>\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"css/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t/* \t        $(\".sideM\").removeClass('active');\r\n");
      out.write("\t\t $(\".itemM\").addClass('active');\r\n");
      out.write("\t\t getHotelItemList(); */\r\n");
      out.write("\t\t$('.datep').datepicker({\r\n");
      out.write("\t\t\tformat : 'dd-mm-yyyy',\r\n");
      out.write("\t\t\tautoclose : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getItem(empId) {\r\n");
      out.write("\t\t $('.delemp').val(empId);\r\n");
      out.write(" \t\t $('.modal').modal('show');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getItem1(itemId) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'getHotelItem.htm',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\titemId : itemId\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype : 'GET',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t$('#info').html('<p>An error has occurred</p>');\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t$(\"input[name='itemName']\").val(data.itemName);\r\n");
      out.write("\t\t\t\t$(\".description\").val(data.description);\r\n");
      out.write("\t\t\t\t$(\"input[name='price']\").val(data.price);\r\n");
      out.write("\t\t\t\t$(\".hid_itemId\").val(itemId);\r\n");
      out.write("\t\t\t\t$(\".btn-addItem\").html(\"Update\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"modal  fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t  <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t\t        <h4 class=\"modal-title\">Are you sure..</h4>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t      <div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t <form action=\"deleteEmp\" method=\"post\">\r\n");
      out.write("\t\t\t\t <input type=\"hidden\" class=\"delemp\" name=\"empId\">\r\n");
      out.write("\t\t\t\t <input type=\"submit\" class=\"btn btn-danger\" value=\"Yes\">\r\n");
      out.write("\t\t\t\t </form>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t    </div><!-- /.modal-content -->\r\n");
      out.write("\t\t  </div><!-- /.modal-dialog -->\r\n");
      out.write("\t\t</div><!-- /.modal -->\r\n");
      out.write("         \r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div id=\"page-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<!--     \t<div class=\"panel panel-default col-sm-12\">\r\n");
      out.write("        \t<div class=\"panel-heading\">Login</div>\r\n");
      out.write("          \t<div class=\"panel-body\"> -->\r\n");
      out.write(" \t\t\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t<thead><tr><th>EMP ID</th>\r\n");
      out.write("\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t<th>Email</th>\r\n");
      out.write("\t\t\t\t<th>Doj</th>\r\n");
      out.write("  \t\t\t\t<th>Contact</th>\r\n");
      out.write("  \t\t\t\t<th>Position</th>\r\n");
      out.write(" \t\t\t\t<th>Salary</th>\r\n");
      out.write("\t\t\t    <th>Delete</th>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody class=\"tbd\">\r\n");
      out.write("\t\t\t\t");
DatabaseConnection db=new DatabaseConnection();
				ResultSet rs=db.selectQuery("select * from employee");
				
				try{
				while(rs.next())
				{
				
      out.write("\r\n");
      out.write("\t\t\t\t\t  <tr><td class=\"description1\">");
      out.print(rs.getString("eid") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description2\">");
      out.print(rs.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description3\">");
      out.print(rs.getString("email") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description4\">");
      out.print(rs.getString("doj") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description5\">");
      out.print(rs.getString("contact") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description6\">");
      out.print(rs.getString("salary") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description7\">");
      out.print(rs.getString("position") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description8\"><a  href=\"javascript:void(0);\" onclick=\"getItem(");
      out.print(rs.getString("eid") );
      out.write(")\">delete</a></td>\r\n");
      out.write(" </tr> \r\n");
      out.write("\t\t\t\t");
} 
				
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				finally
				{
					
					if(rs != null)
						try {
							rs.close();
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					
					db.closeConnection();
					
					
				}
				
				
      out.write("\t\t\t  \r\n");
      out.write("  \t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- </div>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
