/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.8
 * Generated at: 2017-02-18 11:29:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import com.database.DatabaseConnection;
import javax.xml.crypto.Data;

public final class employeeWorking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.database.DatabaseConnection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("javax.xml.crypto.Data");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Employee Working Details</title>\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap-datepicker.js\"></script>\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"css/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Fonts -->\r\n");
      out.write("    <link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <script>\r\n");
      out.write("\t    function daysInMonth(month,year) {\r\n");
      out.write("\t        return new Date(year, month, 0).getDate();\r\n");
      out.write("\t    }\r\n");
      out.write("\t   \t $(document).ready(function(){\r\n");
      out.write("/* \t        $(\".sideM\").removeClass('active');\r\n");
      out.write("\t        $(\".itemM\").addClass('active');\r\n");
      out.write("\t        getHotelItemList(); */\r\n");
      out.write("\t    \t$('.month').datepicker({\r\n");
      out.write("\t    \t\t format: \"mm-yyyy\",\r\n");
      out.write("\t    \t\t viewMode: \"months\", \r\n");
      out.write("\t             autoclose:true\r\n");
      out.write("\t     \t});\r\n");
      out.write("\t        \r\n");
      out.write("\t    \t$('.month').change(function () {\r\n");
      out.write("\t    \t    var date = $('.month').val();\r\n");
      out.write("\t    \t    var month = date.split(\"-\")[0];\r\n");
      out.write("\t    \t    var year = date.split(\"-\")[1];\r\n");
      out.write("\t    \t    var s = daysInMonth(month,year);\r\n");
      out.write("\t    \t    //alert(s);\r\n");
      out.write("\t    \t    $('.workdays').val(s);\r\n");
      out.write("\t    \t});\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    function  salaryResult(){\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t$.ajax({\r\n");
      out.write("\t    \t\t   url: 'ShowSalary',\r\n");
      out.write(" \t    \t\t   type: 'POST',\r\n");
      out.write("\t    \t\t   dataType: 'json',\r\n");
      out.write("\t    \t\t   error: function() {\r\n");
      out.write("\t    \t\t      $('#info').html('<p>An error has occurred</p>');\r\n");
      out.write("\t    \t\t   },\r\n");
      out.write("\t    \t\t   success: function(data) {\r\n");
      out.write("\t     \t\t\t   var boiler = '';\r\n");
      out.write("\t     \t\t\t  if(data.length>0){\r\n");
      out.write("\t                   for(var i=0;i<data.length;i++){\r\n");
      out.write("\t\t\t                 boiler += '<tr>';\r\n");
      out.write("\t\t\t                 boiler += '<td>'+data[i].eid+'</td>';\r\n");
      out.write("\t\t\t                 boiler += '<td>'+data[i].month+'</td>';\r\n");
      out.write("\t\t\t                 boiler += '<td>'+data[i].year+'</td>';\r\n");
      out.write("\t\t\t                 boiler += '<td>'+data[i].workdays+'</td>';\r\n");
      out.write("\t\t \t                 boiler += '<td>'+data[i].totalWorkingHours+'</td>';\r\n");
      out.write("\t\t\t                 boiler += '<td>'+data[i].actualWorkHours+'</td>';\r\n");
      out.write("\t\t\t                 boiler += '<td>'+data[i].actualSal+'</td>';\r\n");
      out.write("\t\t\t                 boiler += '<td>'+data[i].grossSal+'</td>';\r\n");
      out.write("\t\t\t                 boiler += '</tr>';\r\n");
      out.write("\t\t\t              }\r\n");
      out.write("\t                   }\r\n");
      out.write("\t     \t\t\t  else{\r\n");
      out.write("\t     \t\t\t\t boiler += '<tr>';\r\n");
      out.write("\t     \t\t\t\t boiler += '<td colspan=9>Salary for this month already calulated... <button type=\"button\" class=\"btn btn-success\" onclick=\"salaryResult();\">Show Result</button></td>';\r\n");
      out.write("\t     \t\t\t\t boiler += '</tr>';\r\n");
      out.write("\t     \t\t\t  }\r\n");
      out.write("\t              $('.tbd1').html(boiler);\r\n");
      out.write("\t          \t $('.modal').modal('show');\r\n");
      out.write("\t     \t\t   },\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("\t   \r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    function getSalary(eid){\r\n");
      out.write(" \t    \tvar date = $('.month').val();\r\n");
      out.write("    \t    var month = date.split(\"-\")[0];\r\n");
      out.write("    \t    var year = date.split(\"-\")[1];\r\n");
      out.write("\t    \t var year=$('.year').val();\r\n");
      out.write("\t    \tvar workdays=$('.workdays').val();\r\n");
      out.write("\t    \t$.ajax({\r\n");
      out.write("    \t\t   url: 'GetSalaryServlet',\r\n");
      out.write("    \t\t   data: {eid:eid,month:month,year:year,workdays:workdays},\r\n");
      out.write("    \t\t   type: 'POST',\r\n");
      out.write("    \t\t   dataType: 'json',\r\n");
      out.write("    \t\t   error: function() {\r\n");
      out.write("    \t\t      $('#info').html('<p>An error has occurred</p>');\r\n");
      out.write("    \t\t   },\r\n");
      out.write("    \t\t   success: function(data) {\r\n");
      out.write("    \t\t\t   \r\n");
      out.write("     \t\t\t   var boiler = '';\r\n");
      out.write("     \t\t\t   \r\n");
      out.write("     \t\t\t   \r\n");
      out.write("     \t\t\t  if(data.length>0){\r\n");
      out.write("                   for(var i=0;i<data.length;i++){\r\n");
      out.write("                 boiler += '<tr>';\r\n");
      out.write("                 boiler += '<td>'+data[i].eid+'</td>';\r\n");
      out.write("                 boiler += '<td>'+data[i].month+'</td>';\r\n");
      out.write("                 boiler += '<td>'+data[i].year+'</td>';\r\n");
      out.write("                 boiler += '<td>'+data[i].workdays+'</td>';\r\n");
      out.write("                 boiler += '<td>'+data[i].wastedHours+'</td>';\r\n");
      out.write("                 boiler += '<td>'+data[i].totalWorkingHours+'</td>';\r\n");
      out.write("                 boiler += '<td>'+data[i].actualWorkHours+'</td>';\r\n");
      out.write("                 boiler += '<td>'+data[i].actualSal+'</td>';\r\n");
      out.write("                 boiler += '<td>'+data[i].grossSal+'</td>';\r\n");
      out.write("                 boiler += '</tr>';\r\n");
      out.write("              }}\r\n");
      out.write("     \t\t\t  else{\r\n");
      out.write("     \t\t\t\t boiler += '<tr>';\r\n");
      out.write("     \t\t\t\t boiler += '<td colspan=9>Salary for this month already calulated... <button type=\"button\" class=\"btn btn-success\" onclick=\"salaryResult();\">Show Result</button></td>';\r\n");
      out.write("     \t\t\t\t boiler += '</tr>';\r\n");
      out.write("     \t\t\t  }\r\n");
      out.write("              $('.tbd').html(boiler);\r\n");
      out.write("              $('.table-bordered').removeClass('hide');\r\n");
      out.write("    \t \r\n");
      out.write("     \t\t   },\r\n");
      out.write("    \t\t});\r\n");
      out.write("\t    }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("    <div id=\"page-wrapper\" style=\"background-color: #f0f0f0;\">\r\n");
      out.write("    \t<div class=\"container-fluid\">\r\n");
      out.write("\t\t  \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t    <label class=\"col-sm-3 control-label\">Select Month</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t      <input type=\"text\" class=\"form-control month\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t        <label class=\"col-sm-2 control-label\">Select Year</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t      <select class=\"form-control year\">\r\n");
      out.write("\t\t\t      \t<option value=\"2016\">2016</option>\r\n");
      out.write("\t\t\t      \t<option value=\"2017\">2017</option>\r\n");
      out.write("\t\t\t      \t<option value=\"2018\">2018</option>\r\n");
      out.write("\t\t\t      \t<option value=\"2019\">2019</option>\r\n");
      out.write("\t\t\t      \t<option value=\"2020\">2020</option>\r\n");
      out.write("\t\t\t      \t<option value=\"2021\">2021</option>\r\n");
      out.write("\t\t\t      \t<option value=\"2025\">2025</option>\r\n");
      out.write("\t\t\t      \t<option value=\"2026\">2026</option>\r\n");
      out.write("\t\t\t      \t<option value=\"2027\">2027</option>\r\n");
      out.write("\t\t\t      \t<option value=\"2028\">2028</option>\r\n");
      out.write("\t\t\t      \t<option value=\"2029\">2029</option>\r\n");
      out.write("\t\t\t      \t<option value=\"2030\">2030</option>\r\n");
      out.write("\t\t\t      </select>\r\n");
      out.write("\t\t\t    </div>  \r\n");
      out.write("\t\t  \t</div><br><br>\r\n");
      out.write("\t\t  \t<div class=\"form-group\">\r\n");
      out.write("\t\t  \t\t<label class=\"col-sm-3 control-label\">working days of the month</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t      <input type=\"number\" class=\"form-control workdays\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t      \t \r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write(" \t\t\t       <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t       ");
DatabaseConnection db=new DatabaseConnection();
			       ResultSet rs=db.selectQuery("select * from employee");
			      int eid=0;
			      
			      try{
			    	  
			      
			      if(rs.next()){ eid=rs.getInt("eid");
                  session.setAttribute("eid", eid);
			      }
			      
			      } catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					finally
					{
						
						if(rs != null)
							try {
								rs.close();
							} catch (Exception e) {
								// TODO Auto-generated catch block
								e.printStackTrace();
							}
						
						db.closeConnection();
						
						
					}
			      
			      
      out.write("  \r\n");
      out.write("\t\t\t      \t \r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-1\">\r\n");
      out.write("\t\t      \t\t<button type=\"button\" onclick='getSalary(");
      out.print(eid );
      out.write(");' class=\"btn btn-sm btn-danger\" class=\"btn btn-success\">Submit</button>\r\n");
      out.write("\t\t    \t</div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<table class=\"table table-bordered hide\">\r\n");
      out.write("\t\t\t\t<thead><tr><th>EMP ID</th>\r\n");
      out.write("\t\t\t\t<th>MONTH</th>\r\n");
      out.write("\t\t\t\t<th>YEAR</th>\r\n");
      out.write("\t\t\t\t<th>WORK DAYS</th>\r\n");
      out.write("\t\t\t\t<th>WASTED HOURS</th>\r\n");
      out.write("  \t\t\t\t<th>TOTAL WORK HOURS</th>\r\n");
      out.write(" \t\t\t\t<th>ACTUAL WORK HOURS</th>\r\n");
      out.write("\t\t\t    <th>ACTUAL SALARY</th>\r\n");
      out.write(" \t\t\t\t<th>FINAL SALARY</th></tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody class=\"tbd\">\r\n");
      out.write("\t\t\t\t\t<!-- <tr><td class=\"description1\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description2\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description3\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description4\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description5\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description6\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description7\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description8\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"description9\"></td></tr> -->\r\n");
      out.write("  \t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"modal  fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t  <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t\t        <h4 class=\"modal-title\">Salary Detail</h4>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t      <div class=\"table-responsive\">\r\n");
      out.write("\t\t        <table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t<thead><tr><th>Emp Id</th>\r\n");
      out.write("\t\t\t\t<th>Month</th>\r\n");
      out.write("\t\t\t\t<th>Year</th>\r\n");
      out.write("\t\t\t\t<th>Work Days</th>\r\n");
      out.write("\t\t\t\t<th>Total Work Hours</th>\r\n");
      out.write("\t\t\t\t<th>Actual Work Hours</th>\r\n");
      out.write("\t\t\t    <th>Actual Salary</th>\r\n");
      out.write(" \t\t\t\t<th>Final Salary</th></tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody class=\"tbd1\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t    </div><!-- /.modal-content -->\r\n");
      out.write("\t\t  </div><!-- /.modal-dialog -->\r\n");
      out.write("\t\t</div><!-- /.modal -->\r\n");
      out.write("         \r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
