/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.8
 * Generated at: 2017-03-31 08:49:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class booking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>PSCFA</title>\r\n");
      out.write("<meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"looks.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"Minds.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function validateForm() {\r\n");
      out.write("    var x = document.forms[\"myForm\"][\"Email\"].value;\r\n");
      out.write("    var atpos = x.indexOf(\"@\");\r\n");
      out.write("    var dotpos = x.lastIndexOf(\".\");\r\n");
      out.write("    if (atpos<1 || dotpos<atpos+2 || dotpos+2>=x.length) {\r\n");
      out.write("        alert(\"Enter a valid e-mail address\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h2>\r\n");
      out.write("\t\t\t\t<span class=\"description\">\"Book a Flight in Four Simple\r\n");
      out.write("\t\t\t\t\tSteps\"</span>\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t<div class=\"article\">\r\n");
      out.write("\t\t\t\t<h1 class=\"heading\">\r\n");
      out.write("\t\t\t\t\t<a>Enter Details</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<body>\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<table class=\"itin\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th colspan=\"8\"><strong>Pune to New Delhi</strong> &mdash;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tSat, 02 Apr 2016<span class=\"float_right\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Leaves</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Arrives</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Airline</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Flight #</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Class</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Pune<br /> Lohegaon&nbsp; (PNQ)<br /> 05:20 , 02 Apr\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>New Delhi <br /> Indira Gandhi Airport&nbsp; (DEL)<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"weak\">Terminal - 3</span><br> 07:30 , 02 Apr\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Jet Airways</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>9W-364\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Economy</td>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<br> Please Enter Details\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form action=\"Booking\" method=\"POST\" name=\"myForm\" onsubmit=\"return(validateForm())\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t&ensp;Email:&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;<input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" name=\"Email\" required><br> &ensp;\r\n");
      out.write("\t\t\t\t\t\t\tMobile No:&ensp;<input type=\"text\" name=\"Mobile\" required><br>\r\n");
      out.write("\t\t\t\t\t\t\tNo of person:<select id=\"NoOfPerson\" name=\"NoOfPerson\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonchange=\"showDiv(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select> <br>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"one\" style=\"display: block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\tPerson 1 : <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Name\" name=\"Name1\" required><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Aadhar Card Number\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"aad_no1\" required>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"two\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\tPerson 2 : <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Name\" name=\"Name2\" required><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Aadhar Card Number\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"aad_no2\" required>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"three\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\tPerson 3 : <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Name\" name=\"Name3\" required><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Aadhar Card Number\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"aad_no3\" required>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"four\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\tPerson 4 :<br> <input type=\"text\" placeholder=\"Name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"Name4\" required><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Aadhar Card Number\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"aad_no4\" required>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"five\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\tPerson 5 :<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Name\" name=\"Name5\" required><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Aadhar Card Number\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"aad_no5\" required>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<img src=\"images/gallery.png\" class=\"img-center\" alt=\"\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a class=\"active\">1. Search Flight</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"active\">2. Select Flight</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"active\">3. Enter Details</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"next\">4. Book</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"footer\">AISSMS IOIT</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div align=right>© 2017 Ajay Kumar</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
